### PR TITLE
React v15.5 prop types fix

### PR DESCRIPTION
**Pull request by toriaezunama**
React.PropTypes is deprecate in V15.5 so updated to use prop-types library. Also, updated react related libraries to use the latest

### CODE REVIEW

**Comment by schovi** [comment]
@toriaezunama I guess this is breaking change and should be published with new major version. Like when using React older than 15.5 use 1.x otherwise 2.x ?

**Comment by toriaezunama** [comment]
Yes, I agree. Bumping the major version indicates breaking changes and this would break for everyone who isn't on the latest version of React.

**Review by D-TUCKER — APPROVED** [review]

**Comment by oallouch** [comment]
Hi everyone,
Any release planned ?

**Comment by schovi** [comment]
@oallouch: I am on it!

**Review by schovi — APPROVED** [review]

**Comment by schovi** [comment]
@oallouch @toriaezunama 

It is up as 2.0.0
Check it please.

**Comment by oallouch** [comment]
All good for me.

**Comment by toriaezunama** [comment]
Thanks.

**Pull request merged**
